### ISSUE TITLE
Remove usage of kernel32-sys crate

### ISSUE THREAD

**Issue by atouchet** [notify-rs/notify#168]
kernel32-sys is no longer used with winapi 0.3 and should have been removed in https://github.com/passcod/notify/pull/162/commits/d7232ce5762b3749ad5ed88c03490bfb1f246f94.

**Comment by passcod** [comment]
Thank you!

**Comment by passcod** [comment]
(I don't doubt you, but this is a tad more complex to migrate away from than the 'whoops let's remove the crate' I thought I'd do this morning)

**Comment by ErichDonGubler** [comment]
Looks like this is already done?

**Comment by atouchet** [comment]
> Looks like this is already done?

https://github.com/passcod/notify/blob/0709c940dd7294ef07b176504a89949d462bbe98/Cargo.toml#L45

Nope.

**Comment by ErichDonGubler** [comment]
@atouchet: Gah, derp. I saw the above commit referenced and made a poor assumption. Apologies!

**Comment by atouchet** [comment]
This was done in #217.
