### ISSUE TITLE
Push minimum to Rustc 1.32

### ISSUE THREAD

**Issue by passcod** [notify-rs/notify#201]
This is a [major; breaking].

Comment here with things that can be changed/upgraded with this move. 1.32 supports the 2018 Edition.

Looking forward I also want to establish a strategy for pushing the minimum rustc up more regularly: one thought is to support at least N months of rustc, but be free to upgrade from older stuff. However, I intend to maintain the "pushing the minimum rustc is a breaking change" guarantee.

Another way is to allow majors to optionally push the minimum rustc as far as they want (up to the latest stable as of release), but only allow one such push every six months or every year (unless exceptional circumstances), and be conservative about those pushes.

**Comment by passcod** [comment]
#199 and #200: filetime crate.

**Comment by 0xpr03** [comment]
I'm closing this as v5 is already on 1.47 as MSRV.

> Looking forward I also want to establish a strategy for pushing the minimum rustc up more regularly: one thought is to support at least N months of rustc, but be free to upgrade from older stuff. However, I intend to maintain the "pushing the minimum rustc is a breaking change" guarantee.

I'd only do further MSRV pushes on new major versions (and if only for that matter). cc @JohnTitor in case you disagree with this.
