### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by passcod** [notify-rs/notify#209]
As per the abandonment announce, copied here for convenience:

> Notify has been years of my life and as much as it’s a tough decision, I’m also greatly relieved. It’s been great, it’s been not so great; it’s now time. I got some distance, took a hard look at it all, and realised I don’t want to do this any more. For way longer than I should have let this go on for, Notify sparked negative joy, and I’m Marie-Kondo-ing it out.
>
> The logistics: several people have commit bit, and several people have publish bit, and the project is also covered by the [Rust Bus](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046).
>
> If you want to take over or get commit/publish bits and you’re a trusted/respected community member, just ask. If you’re not a trusted/respected community member, try forking first.
>
> I will not merge PRs, I will not commit unless it’s an emergency, I will not respond to issues or comments unless I really really feel like it, and the goal is total disengagement.\*
>
> So Long 🔭 And Thanks For All The Fish 🐬

\* As an addendum, though, I'm happy doing some light admin and light mentoring / answering questions about current and future design and code, during the transition period, as long as that takes.

There's also some comments on Twitter:

- at the original announce: https://twitter.com/passcod/status/1168188637361725442
- at this quoting thread: https://twitter.com/yaahc_/status/1168217915285372928

@Dylan-DPC has expressed some interest in helping to create an organisation and taking this forward.

This is a call for anyone else who would be interested in maintainership!

**Comment by Dylan-DPC** [comment]
If you want to help contributing to this crate, please level a comment below

**Comment by passcod** [comment]
I can also hand over the repo and crate to @rust-unofficial if that's a better venue, especially for a crate which may have community importance (as it's used in many projects). /cc @badboy

**Comment by 0xpr03** [comment]
I'm interested in getting 5.0 over the edge. I can try to help if pointed towards issues.

**Comment by passcod** [comment]
There's no nearby edge for 5.0. OK. So, for people, here's a quick view of what was in my head for 5.0 and further. Obvi no need to adhere to all or part of it.

- From 0 to 4, the event type was essentially a bitfield, hence it could contain many different kinds of events on the same structure, but it's very limited in what it could express. Further, the event type was a simplification of the inotify native bitfield, so it was kinda fit for that, and then other native api event semantics were retrofitted on top. Kind of a mess. So I redesigned the event type to only contain one semantic action at a time, and have a hierarchical structure that covers _more_ than all native systems I looked at _combined_, with possibility for expansion in several ways. Then there's a Vec of PathBufs, so events can describe that they apply to several paths, with semantics left in the air here at this point (the thinking being that for most events it should be length == 1, but for renames where both sides are known it would be [original, new]).
- The original idea with the new event type was that it would go in the next branch of notify, which was a complete rewrite. However, I started to burn out, and at some point figured that the next branch would likely never get finished at that rate, so I may have better luck retrofitting the finished parts of Next onto the existing code, as a kind of transitive step and to rebuild momentum.
- That posed a larger problem that I didn't immediately realise. All the old code works on the assumption that events may contain multiple event kinds. There's various manipulations here, e.g. we can transform one event into another by adding in the bit for the new type and then later remove the bit for the old type, sometimes in completely different parts of the code, with potentially complex interactions in between. And often, the code expected one event to go in, and one event to go out, and the in and out could have any amount of actual semantic actions on them.
- There were also bigger issues I could start to see take shape with how the debounce code worked. But anyway, what I did was I ripped out all that I could see of the debounce code and got 5.0 with only immediate API mostly working.
- So the first step is to remake the debounce code for 5.0. There's many approaches and idk which is good, so I won't comment on that.
- Second step is to integrate or re-integrate the new options system that was made for the OngoingEvents feature.
- Third step, which may be better done interleaved with 1&2 is to make the NoticeEvents an optional feature as per this option system.
- Four is to hide event type unless the PreciseEvents option is on.
- Five is to review and get a stable release out.
- Six is to get a 5.1 with the new channel-less API as in the readme, or as per @matklad's last suggestion in #204 (iirc).
- Seven is to get a 5.2 with precise events filtered at the kernel level if/when possible? dunno.
- Then there's the stretch goals later of:
  - Adding a watchman backend
  - Fixing all bugs lol

That's it! Enjoy

**Comment by Dylan-DPC** [comment]
> @Dylan-DPC I like the idea of creating a dedicated organisation along the lines of notify-devs for managing notify. Perhaps this way it might make it easier for multiple folks to share the maintenance burden?

yes that's the exact reason behind it

**Comment by ashleygwilliams** [comment]
hey folks!  just to clarify- my package "notify forked" really only exists because we ran into a semver issue yesterday and are preparing a release of a project that uses notify. i dont really intend to do any feature work- just bug fixes so the project i do for work can continue to use notify for the time being. that being said, i am able to help with some things, triage, etc, so do let me know if i can help!

**Comment by mitchmindtree** [comment]
@passcod thanks for the detailed explanation!

@Dylan-DPC sounds great to me! Would you like to start the organisation? Then perhaps the initial maintainers could include yourself, @passcod (at least while they assist with the transfer), @ashleygwilliams, @0xpr03? I'd also be welling to help every now and then. Perhaps between all of us we can keep notify above water until someone more dedicated comes along and we can add them to the org as well?

**Comment by Dylan-DPC** [comment]
@mitchmindtree yes will do when I get time later this week

**Comment by dhiemaz** [comment]
> @passcod thanks for the detailed explanation!
> 
> @Dylan-DPC sounds great to me! Would you like to start the organisation? Then perhaps the initial maintainers could include yourself, @passcod (at least while they assist with the transfer), @ashleygwilliams, @0xpr03? I'd also be welling to help every now and then. Perhaps between all of us we can keep notify above water until someone more dedicated comes along and we can add them to the org as well?

I am willing to help also..

**Comment by metadave** [comment]
I'm willing to help/maintain, although I need to read more of the source to get up to speed.

**Comment by JohnTitor** [comment]
@passcod @Dylan-DPC Hi, I'm interested in maintaining this crate.

**Comment by passcod** [comment]
As @Dylan-DPC said elsewhere, looks like this is resolved :)

**Comment by JohnTitor** [comment]
Can it be closed?

**Comment by dhiemaz** [comment]
If it resolved then can closed it..

**Comment by JohnTitor** [comment]
Okay, I'm going to close this, but feel free to re-open if this is still needed.

**Comment by Dylan-DPC** [comment]
Yes it's resolved but it's not the end - in case anyone reading this in future would like to maintain this crate in future, just leave a comment here :)
