### ISSUE TITLE
CI Broken

### ISSUE THREAD

**Issue by 0xpr03** [notify-rs/notify#216]
CI seems currently to be broken and must be enabled for the organization.
CC @Dylan-DPC @passcod

**Comment by passcod** [comment]
Travis is now at https://travis-ci.com/notify-rs/notify

**Comment by passcod** [comment]
Appveyor is at https://ci.appveyor.com/project/notify/notify

**Comment by 0xpr03** [comment]
Yep, works. Just had to force-push my PR.
