### ISSUE TITLE
Request: publish a new 5.0.0-pre.2 crate

### ISSUE THREAD

**Issue by itkovian** [notify-rs/notify#233]
The README shows 5.0.0-pre.2 in the dependencies section. 

Would it be possible to also publish the current state of this code for that version? I am currently depending on notify, but still using the commit ID, which disallows me from publishing to crates.io.

**Comment by JohnTitor** [comment]
I'm not sure we're ready to publish `5.0.0-pre.2`, could we make a new pre-release? @notify-rs/watchmakers

**Comment by 0xpr03** [comment]
I'm for making a new pre-release.

**Comment by 0xpr03** [comment]
The current regressions (and never working tests) are making it hard to decide how to move forward, so I'm for a pre-release. I fear we'll need to invest some amount of work to get back to a clean state on all supported platforms.

**Comment by itkovian** [comment]
Thanks for considering.

**Comment by JohnTitor** [comment]
I'm fine with making new a pre-release since the absence of tests seems intentional in changelog (and it's just a pre-release). If anyone has no concerns, I'll make a new pre-release with current main branch.
CC: @notify-rs/watchmakers

**Comment by Dylan-DPC** [comment]
I'm fine with a new pre release as well

**Comment by JohnTitor** [comment]
Okay, just published `5.0.0-pre.2`. Any feedback is welcome!

**Comment by dhiemaz** [comment]
I'm fine as well..
