### ISSUE TITLE
upgrade winapi dependency to 0.3

### ISSUE THREAD

**Issue by alexanderkjall** [notify-rs/notify#235]
This is a feature request, I'm working on packaging this crate for debian, since I use the crate in ripasso ( https://github.com/cortex/ripasso/ ), and I'm trying to package that for debian.

Debian is unwilling to package the kernel32 crate, since it's outdated and a newer version exist, see https://github.com/retep998/winapi-rs#should-i-still-use-those--sys-crates-such-as-kernel32-sys

It would therefor be nice to upgrade the dependency in notify in order to be able to get it into debian.

for reference: https://salsa.debian.org/rust-team/debcargo-conf/merge_requests/78

Would this be a change that makes sense?

**Comment by JohnTitor** [comment]
Hm, notify v4.0.14 and 5.0.0-pre.1 use `winapi ^0.3.5` as a dependency. I guess mio v0.6.x uses winapi v0.2.x so notify requires kernel32-sys. We should wait for updating mio and mio-extras.

**Comment by JohnTitor** [comment]
Ah, we should also make a new release including #217.

**Comment by JohnTitor** [comment]
Released `4.0.15` and `5.0.0-pre.2`, we stopped depending on winapi 0.2.x and kernel32-sys directly. Could we close this issue?

**Comment by alexanderkjall** [comment]
Thanks a lot :)
