### ISSUE TITLE
Clarify licensing situation

### ISSUE THREAD

**Issue by atouchet** [notify-rs/notify#243]
According to the Readme:

> Notify was undergoing a transition to using the Artistic License 2.0 from CC Zero 1.0. A part of the code is only under CC0, and another part, including all new code since commit 3378ac5a, is under both CC0 and Artistic. When the project was to be entirely free of CC0 code, the license would be formally changed (and that would have incurred a major version bump). As part of this, contributions to Notify since would agree to release under both.

Is this still accurate under this crate's new maintainership? Is the plan still to transition to Artistic License 2.0?

**Comment by 0xpr03** [comment]
Hm, according to https://github.com/notify-rs/notify/issues/158 the relicense already happened.
Though the change introduced states that the LICNSE file is to be used. Which is still CC0 (which is AFAIK not a valid license due to multiple problems).
CC: @passcod

**Comment by passcod** [comment]
CC0 is what all of the code is still under, with some parts optionally licensable as Artistic 2.0. I have no strong opinions on the validity of CC0 as a software license, or on the choice of license for this project going forward. The concept of "relicensing" a work that explicitly puts itself outside of copyright is non-sensical anyway, and #158 was more about consultation and respect than legal requirement.

**Comment by passcod** [comment]
Also #158 was for the next branch, which was a complete rewrite and contained zero prior code, and has no bearing on the main branch, including 4.x and 5.x release series.

**Comment by 0xpr03** [comment]
@passcod what would you say about relicensing this to the typical MIT/Apache2 dual lience of most crates ? I'd like to close this.

**Comment by passcod** [comment]
Not sure of the legal issues but if you think it's all clear I have no objections and give whatever permission may be needed to relicense my code in this project to any open source license.

**Comment by 0xpr03** [comment]
Hm so I'd like to not end up like https://github.com/blackbeam/rust-mysql-simple/issues/36 maybe @JohnTitor knows something ?

**Comment by JohnTitor** [comment]
[We _can use_ CC0 for Notify](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) and re-licensing requires all the contributors' agreement (as @0xpr03 mentioned) so I'd like to avoid it as possible.
And apart from CC0, at least we have to add `Artistic-2.0` to Cargo.toml.
