### ISSUE TITLE
Are file change notifications atomic?

### ISSUE THREAD

**Issue by SirWindfield** [notify-rs/notify#244]
To give more background information: My goal is to create a watcher daemon that checks for changed files in a directory and only if they are completely written to the disk, the daemon will perform some analysis. According to the `5.0.0` docs there seems to be only event kinds for file changes. However, I couldn't find more details about writes to those files.

I can imagine that I might run into edge cases where the OS might write the file in a non-atomic way, my daemon would see that the file changed and try to analyse a broken file because the write process didn't finish properly.

Could this happen when using `notify`? Is it also possible to only listen for file writes and not specific metadata changes (as those would trigger a file change as well).

**Comment by 0xpr03** [comment]
Is still relevant ? Otherwise I'd like to close stale issues.

Yes notify doesn't prevent you from reading invalid files. Specifically if you use the non-debounced watcher you might see a file truncat before a complete write and thus read an invalid version.
