### ISSUE TITLE
Add proper debouncer

### ISSUE THREAD

**Issue by skorokithakis** [notify-rs/notify#262]
Currently, the debouncer actually only collapses events. It would be useful if the debouncer could ignore all events until the timeout occurred, and then reported all of them at once.

This is useful for letting the changes "settle", ie have an idle period before attempting to e.g. copy files to a remote server.

**Comment by 0xpr03** [comment]
What exactly would expect to get from receiving all events as batch ? You can already do this by yourself with more control.
