### ISSUE TITLE
Mistake in doc link

### ISSUE THREAD

**Issue by Boscop** [notify-rs/notify#264]
Go to this page https://docs.rs/notify/5.0.0-pre.3/notify/#with-precise-events
and click on `event`, it's a link to https://docs.rs/notify/5.0.0-pre.3/notify/event/index.html%60
which has an erroneous `%60` at the end.

**Comment by JohnTitor** [comment]
It was fixed by #256 but we haven't made a release for it. Opened #265.

**Comment by JohnTitor** [comment]
Released v5.0.0-pre.4 (https://crates.io/crates/notify/5.0.0-pre.4) and should be updated the docs on docs.rs in a few hours. Thanks for reporting!
