### ISSUE TITLE
Add inotify support on BSD

### ISSUE THREAD

**Issue by chrisduerr** [notify-rs/notify#273]
So a while back someone reported the following issue to Alacritty: https://github.com/alacritty/alacritty/issues/3871

This isn't much of a surprise, it looks like notify's BSD implementation is just using the worst, most general fallback which causes high system load due to a relatively high poll rate set by Alacritty.

But it seems like at least some BSDs do have the ability to support inotify and might potentially have other native APIs too (I'm not familiar with those at least). I'm curious if this has been investigated, I'd assume that BSD just has not been a priority?

**Comment by deepy** [comment]
For BSD support you'd probably want kqueue, which has the benefit of also being supported on macOS.
Judging by #136 and #117 there seems to be some interest but mostly everything seems abadoned

**Comment by xanderio** [comment]
With #335 merged, i don't think this is necessary any more.
