### ISSUE TITLE
Docs example for hot reloading

### ISSUE THREAD

**Issue by vladinator1000** [notify-rs/notify#275]
Hi y'all, I've been trying to figure out how to reload a struct on a file change and was thinking the docs could really use an example of that. I got somewhere but my current solution panics [here](https://github.com/savovsa/announcer/commit/c21c0c0f36f4982f1092398094094720481ca05c#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR24) when you save the file too often. It seems that it's passing [nothing to Serde](https://github.com/savovsa/announcer/commit/c21c0c0f36f4982f1092398094094720481ca05c#diff-121f57fd9da9016a85108d2a879fdc4e8d03e3699857e7528d90f2199229153fR35) for deserialization.

Here's the error
`EOF while parsing a value at line 1 column 0`

I should also mention this is on Windows and it seems that windows fires 2 Modify Any events whenever you save the file.

**Comment by 0xpr03** [comment]
Depending on how your editor works its quite possible that your config file is truncated (empty) and then the new content is added. So for a brief moment an EOF is read as the file is empty.

**Comment by vladinator1000** [comment]
@0xpr03 thank you, I added some error checks for that! Do you mind if I add a more complex example to the examples folder that looks a bit [like this](https://github.com/savovsa/announcer/blob/mutex/src/main.rs)?

**Comment by 0xpr03** [comment]
Hm, that may be ok. On the other side I'd hope that people are not using notify-rs for async stuff ? I mean tokio and async-std come with their own file watchers AFAIK?

**Comment by vladinator1000** [comment]
Hmm I don't see any support for that in async-std. Notify-rs seems to work great for my use case of hot reloading so far.

**Comment by 0xpr03** [comment]
Then I'd be fine with adding an example. At best add some kind of comment to document what you're trying to accomplish (sync notify -> async code etc)

**Comment by 0xpr03** [comment]
Feel free to close this due t #279 being merged.
