### ISSUE TITLE
Feature request: Implement From<Error> for io::Error

### ISSUE THREAD

**Issue by bbarker** [notify-rs/notify#292]
This is for better ergonomics with a common Error type, see e.g. the discussion at https://docs.rs/path_abs/0.5.1/path_abs/struct.Error.html

**Comment by bbarker** [comment]
Apparently this already exists, I must just be doing it wrong.

**Comment by bbarker** [comment]
Looks like what I actually need is `impl From<Error> for io::Error`

**Comment by 0xpr03** [comment]
I'm not sure what you want to achieve with that exactly. If you mean the trait, we [do implement that already](https://docs.rs/notify/5.0.0-pre.6/notify/struct.Error.html#impl-Error). If you mean [std::io::Error](https://doc.rust-lang.org/std/io/struct.Error.html) this won't work. `notify::Error` is not only an `io::Error`, so a conversion may totally fail. This is true for version [4](https://docs.rs/notify/4.0.15/notify/enum.Error.html) and [5](https://docs.rs/notify/5.0.0-pre.6/notify/enum.ErrorKind.html). Thus only [try_from](https://doc.rust-lang.org/std/convert/trait.TryFrom.html#tymethod.try_from) could be implemented and will fail for every other case than `Error::Io`.

If you want to easily wrap different errors with a unified type to return I suggest using [anyhow](https://crates.io/crates/anyhow) or [thiserror](https://crates.io/crates/thiserror) that handle easily wrapping multiple error kinds without rolling your own complete error type (or boxing). There are multiple other error crates out there that may better fit your needs.

**Comment by bbarker** [comment]
Thanks for pointing out `anyhow`, I think that basically solves the issue in a more generic way than I had in mind, so I'll close this.
