### ISSUE TITLE
Not detecting changes for ~/.bash_history

### ISSUE THREAD

**Issue by Selyatin** [notify-rs/notify#295]
#### System details

- OS/Platform name and version: Kubuntu 20.10
- Notify version: 4.0.15

#### What you did (as detailed as you can)
I've simply added ~/.bash_history to watch via the absolute path like /home/user/.bash_history.
The watcher is in Raw mode.

#### What you expected
For the watcher to detect changes.

#### What happened
It didn't detect any changes whatsoever.

**Comment by 0xpr03** [comment]
Could you please post your code ? I can't reproduce this on Kubuntu 20.04 with my homefile and it should make no difference.

**Comment by 0xpr03** [comment]
Also what are you doing that you expect something to change ?
If I open 1 Konsole instance, run a command and then quit it, I can see the changes. Note that multiple instances [won't necessarily](https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows) write to .bash_history.

**Comment by Selyatin** [comment]
let path = "/home/user/.bash_history";
`     if let Err(err) = watcher.watch(path, RecursiveMode::NonRecursive){
            return Err(format!("Error while trying to add log at path {} to watch: {}", path, err.to_string()));
        }
`
Simply adding .bash_history to watch. This probably is not an issue that's related to notify-rs I think, because it's working just fine with any other file, it's most likely as you've suggested that it's related to the writing trigger for history to write the executed commands into .bash_history and not to detecting the change.

**Comment by 0xpr03** [comment]
Note also that some software does file writes that will simply re-create the file instead of rewriting it. Meaning that watching only the current file won't detect what you want.
