### ISSUE TITLE
Feature: Option to pass "ID" to `Watcher::watch` to map events more efficiently to handlers

### ISSUE THREAD

**Issue by d4h0** [notify-rs/notify#300]
At the moment, if we watch several targets, we have to analyze the event path to find out for which path the event was triggered:

```rust
use std::sync::mpsc::channel;
use std::time::Duration;

fn main() {
    let (tx, rx) = channel();
    let mut watcher = watcher(tx, Duration::from_secs(10)).unwrap();
    
    watcher.watch("/home/test/foo-files", RecursiveMode::Recursive).unwrap();
    watcher.watch("/home/test/bar-files", RecursiveMode::Recursive).unwrap();

    loop {
        match rx.recv() {
           Ok(event) => {
               // Here we have to analyse the path of the
               // event to find out for which directory it is
               todo!()
           }
           Err(e) => println!("watch error: {:?}", e),
        }
    }
}
```

This is less efficient and more cumbersome than it could be, I believe.

What I propose, is to add a method like `Watcher::watch_with_id` that accepts an ID that we can use to map the event to the watch target efficiently and ergonomically.

Basically, something like this:

```rust
use notify::{Watcher, RecursiveMode, watcher};
use std::sync::mpsc::channel;
use std::time::Duration;

#[derive(Debug)]
enum WatchTarget {
    Foo,
    Bar,
}

fn main() {
    let (tx, rx) = channel();
    let mut watcher = watcher(tx, Duration::from_secs(10)).unwrap();
    
    watcher.watch_with_id(WatchTarget::Foo, "/home/test/foo-files", RecursiveMode::Recursive).unwrap();
    watcher.watch_with_id(WatchTarget::Bar, "/home/test/bar-files", RecursiveMode::Recursive).unwrap();

    loop {
        match rx.recv() {
           Ok((id, event)) => {
               // Now we can use an efficient and ergonomic match block:
               match id {
                   WatchTarget::Foo => todo!(),
                   WatchTarget::Bar => todo!(),
               }
           }
           Err((id, e)) => println!("watch error for target {:?}: {:?}", id, e),
        }
    }
}
```

This also could be used to pass additional data to specific event handlers (so maybe something like `Watcher::watch_with_data` would be a better name), which would be nice.

**Comment by 0xpr03** [comment]
I don't see how we could differentiate between different paths. `/home/test/foo-files` could contain symlinks (which some people want to resolve) and thus we can't really tell where each path is coming from. The way folders are resolved differs also for each OS or method. Thus on linux we have to scan the whole tree, while on windows this is unnecessary and thus would add more overhead that each driver would have to implement.
You're probably better off implementing this recursive traversing system yourself (for example with [walkdir](https://crates.io/crates/walkdir) ) to differentiate between your targets.

**Comment by d4h0** [comment]
Thanks for your reply, @0xpr03!

This sound like I know less about file systems than I thought... :)

> I don't see how we could differentiate between different paths.

I assumed erroneously, the OS would return some kind of ID that indicates which file system monitor request triggered an event.

> You're probably better off implementing this recursive traversing system yourself (for example with walkdir ) to differentiate between your targets.

So currently, I use something the following:

```rust
        let path1 = PathBuf::new("/home/test/foo-files");
        let path2 = PathBuf::new("/home/test/foo-files");

        match rx.recv() {
           Ok(UnbounsedEvent::Write(path) => {
               if path.starts_with(path1) {
                   // handle path1 events
               } else if path.starts_with(path2) {
                   // handle path2 events
               } else { .. }
           }
           ..
        }
```

Do you mean, this could lead to problems if symlinks are involved?

**Comment by 0xpr03** [comment]
> Do you mean, this could lead to problems if symlinks are involved?

Yeah that's something I'll have to check.

> I assumed erroneously, the OS would return some kind of ID that indicates which file system monitor request triggered an event.

No, first of all there is no "the OS" there are > 3 with different systems, and possibly multiple for one OS. So what you probably want to do is to initiate notify 2 times for two folders, this is the kind of "different code".

>I use something the following

For your code:
This is only true as long as all paths are starting with this kind of path. I'll have to test if that holds true. My assumption is that /foo/var could symlink to /baz and may be reported as /baz so you won't get /foo as starting path to match against.

That said, if the method you're applying is working for you (matching prefixes) I don't even see why notify should expose some IDs, as your method is more powerful. (For example using a HashMap with something like <start path|function> to react dynamically, supporting user defined regexes for different files etc.)

**Comment by d4h0** [comment]
> if the method you're applying is working for you (matching prefixes) I don't even see why notify should expose some IDs, as your method is more powerful.

In my actual code, such an API would simplify the code a bit, and I assumed what I do is a common use-case. I also assumed erroneously that `notify` could do this without matching paths, which would be more efficient (on the other hand, this is probably not very important for most code that uses `notify`).

Anyway, this feature isn't essential, and if it is difficult to implement (as it seems), `notify` shouldn't.

Thanks for answering my questions, @0xpr03!
