### ISSUE TITLE
Cutting 5.0.0-pre.10 to incorporate the soundness fix?

### ISSUE THREAD

**Issue by erickt** [notify-rs/notify#326]
Thanks for merging in https://github.com/notify-rs/notify/pull/325, would it be possible to cut another release to include this fix?

**Comment by 0xpr03** [comment]
Yeah I'll do one tomorrow when my headache is hopefully gone

**Comment by erickt** [comment]
Thanks! hope you feel better!

**Comment by 0xpr03** [comment]
Sorry for the delay, got into urgent stuff. It's released now.
