### ISSUE TITLE
Proposal: kqueue support based on polling crate 

### ISSUE THREAD

**Issue by xanderio** [notify-rs/notify#327]
I'm currently looking into adding support for kqueue to support BSD platforms.

After a bit of digging i found the [polling](https://crates.io/crates/polling) crate from the smol-rs team.
The crate it self lists macOS, iOS, FreeBSD, NetBSD, OpenBSD, and DragonFly BSD as supported platforms for kqueue.  

Would PR adding polling based KqueueWatcher be accepted?

**Comment by 0xpr03** [comment]
Yep, see #273 (and also (here)[https://github.com/notify-rs/notify/issues?q=is%3Aissue+is%3Aopen+kqueue] for all the kqueue mentions about better support through that ;) )

**Comment by 0xpr03** [comment]
A bit of warning though: The current structure/implementation for the other systems is a little bit blurry as some stuff got changed/removed without a real new replacement. See for example [here](https://github.com/notify-rs/notify/pull/286#issuecomment-821239651). It's totally fine if you just copy the feature parity of the inotify implementation (for which I can speak) and not implement for example the precise config optionality. Still I'd welcome some hints in the code for `unsafe` for why it's safe and where you'd have to flip something to reach/implement unprecise* events.

\* With unprecise I mean the [PreciseEvents](https://docs.rs/notify/5.0.0-pre.9/notify/enum.Config.html#variant.PreciseEvents) option we want to reach.
