### ISSUE TITLE
Watcher not doing anything

### ISSUE THREAD

**Issue by ByteAlex** [notify-rs/notify#351]
Hello!

Today I encountered a problem which I was not able to solve, please find the details below.
Thank you in advance.

#### System details

- OS: Windows 10 Version 20H2
- Rust version: 1.53.0
- Notify version: 5.0.0-pre.12 / (same behaviour on 4.0.17)
- Running as normal user (unprivileged)

#### What you did (as detailed as you can)
I tried to do a simple watcher, which just reports an event to stdout.
I've tried it on different Paths (Full path to a specific location, local dir ".", std::env::current_dir()), while the local dir / current dir are the target folders in which I built the code, which are located in a subdirectory of my user account.

Code:
```rust
use log::{info, error};
use notify::{RecursiveMode, Watcher};
[..]
    pub fn start_watcher(&self) {
        let mut watcher = notify::recommended_watcher(| result: notify::Result<notify::Event> | {
            match result {
                Ok(event) => info!("Event: {:?}", event),
                Err(err) => error!("Error: {:?}", err)
            }
        }).unwrap();
        watcher.configure(notify::Config::OngoingEvents(Some(core::time::Duration::from_secs(1)))).unwrap();
        let buf = std::env::current_dir().unwrap();
        info!("Watching {}", buf.display());
        watcher.watch(buf.as_path(), RecursiveMode::Recursive).unwrap();
    }
```
I get the "Watching .." output with the correct directory, yet no other events are reported, even though I deleted, created, renamed, changed files in the directory which the stdout printed.
I also tried pressing F5 and the "refresh" button in the explorer.exe.

#### What you expected
Events being printed within the configured delay, as I change

#### What happened
No output was generated, except the "Watching..."

**Comment by 0xpr03** [comment]
Your start_watcher function doesn't return the watcher and simply drops it on exist. Thus the watcher "guard" is dropped and kills its event loop. You'll have to keep the watcher variable somewhere as long as you want it to do something.

**Comment by ByteAlex** [comment]
That worked! Thanks for your explanation. I did not think of this, sorry for being dumbish.
