### ISSUE TITLE
Report which sub-path failed when adding a Recursive watch and a subfolder has a permission (or other) error

### ISSUE THREAD

**Issue by passcod** [notify-rs/notify#353]
#### System details

- OS/Platform name and version: Linux (inotify backend, probably happens on windows too)
- Rust version (if building from source): `rustc --version`: 1.54.0
- Notify version (or commit hash if building from git): 4.x and 5-pre.12

- If you're coming from a project that makes use of Notify, what it is, and a link to the downstream issue if there is one: https://github.com/watchexec/watchexec/issues/149

#### What you did (as detailed as you can)

This directory structure:

- . (working directory)
  - `folder1` (owned by user)
  - `folder2` (owned by user)
    - `folder3` (owner by root)

```rust
let mut w = RecommendedWatcher::new(|ev| println!("{:?}", ev));
w.watch(Path::new("folder1"), RecursiveMode::Recursive)?;
w.watch(Path::new("folder2"), RecursiveMode::Recursive)?;
```

#### What you expected

For the second `watch()` to error when recursing for `folder3` and the `Error`'s `paths` field to be `["folder2/folder3"]`.

#### What happened

The second `watch()` errors, but the error has an empty `paths` field:

```
Error {
    kind: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" }),
    paths: []
}
```

---

Also, very love what you've done with Notify, looking forward to the stable 5.0 release! ❤️

**Comment by 0xpr03** [comment]
Heyho, yeah I suppose we'll need to fix this in [here](https://github.com/notify-rs/notify/blob/ea7d8b0cdd2f47c829eca8f05498a02da79b59a7/src/inotify.rs#L492) for inotify, but from my understanding we can't fix this correctly on windows, as recursive flags are [handled](https://github.com/notify-rs/notify/blob/ea7d8b0cdd2f47c829eca8f05498a02da79b59a7/src/windows.rs#L285) by the [windows API](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw), so we don't have any context what we failed to watch. Will also have to look into the BSD and darwin implementation.

**Comment by passcod** [comment]
I've done it for inotify, will PR. Looking into kqueue now.

**Comment by 0xpr03** [comment]
Ah that is fast :)

**Comment by passcod** [comment]
- inotify: done, in PR
- Kqueue: done, in same PR
- Windows: as you said, handled by Windows, so no visibility. I've still added some path info in places.
- Darwin/FSEvents handles its recursion itself, so no visibility either. What path info we know about was already all there!
- Polling: was already all good.
