### ISSUE TITLE
kqueue debug messages

### ISSUE THREAD

**Issue by netthier** [notify-rs/notify#356]
#### System details

- OS/Platform name and version: FreeBSD 13.0-RELEASE-p3
- Rust version (if building from source): `rustc --version`: rustc 1.54.0 (a178d0322 2021-07-26)
- Notify version (or commit hash if building from git): notify-5.0.0-pre.12

- If you're coming from a project that makes use of Notify, what it is, and a link to the downstream issue if there is one: Trunk (a WASM web application bundler for Rust)
- Filesystem type and options: ZFS

#### What you did (as detailed as you can)
I tried using Trunk to compile and serve a WebAssembly binary

#### What you expected
Clean console output.

#### What happened
The trunk output contained *a lot* of debug messages originating from notify, here's an example:
```
[/home/lmt/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0-pre.12/src/kqueue.rs:145] &event = Event {
    ident: Filename(
        16,
        "/path/to/project/frontend/dist",
    ),
    data: Vnode(
        Write,
    ),
}
```
The reason for these is quite obviously the `dbg!()` statement [here](https://github.com/notify-rs/notify/blob/main/src/kqueue.rs#L145)
It makes trunk's output almost unreadable, so I'm wondering if it's really necessary.

**Comment by 0xpr03** [comment]
That is definitely an oversight by me reviewing #335, will fix that.
