### ISSUE TITLE
Which Watcher do I get?

### ISSUE THREAD

**Issue by jhscheer** [notify-rs/notify#361]
I would like to know which Watcher `RecommendedWatcher::new()` returns.

For example if `let mut watcher = RecommendedWatcher::new(tx)?;` returns a `PollWatcher` I would like to set the delay manually (the default is 30 seconds and cannot be adjusted later).

Maybe something like,

1. either add an `Option<Duration>` parameter to `Watcher::new()` which will be relevant only if `type RecommendedWatcher = PollWatcher;` Then I could call `let mut watcher = RecommendedWatcher::new(tx, Some(Duration::from_secs(1)))?;`
2. or add a `whoami()` method to the Watcher trait and implement setting the delay with `configure()`. Then I could call, e.g. 
```rust
let mut watcher = RecommendedWatcher::new(tx)?;
if watcher.whoami == WatcherType::PollWatcher {
    watcher.configure(Config::SetDelay(Duration::from_secs(1)))?;
}

**Comment by 0xpr03** [comment]
The idea isn't bad, we'll need to add an enum for each type that is part of the trait, you can do a PR if you want.
FYI: You should only get the pollwatcher on anything that's not *BSD,*nix*,Windows,MacOS.

**Comment by 0xpr03** [comment]
I've got an implementation that sidesteps adding the params for PollWatcher to the trait.
