### ISSUE TITLE
Create Event for kqueue missing

### ISSUE THREAD

**Issue by jhscheer** [notify-rs/notify#365]
I'm using kqueue backend on macOS because FSEvents is not suitable (#240) for my use case.
However I noticed there's no `CreateKind` for kqueue implemented.
Is this a limitation of kqueue or an oversight?
If it's the former, is there maybe a workaround for this?

I can get a Remove(Any) event if the "Path" I'm watching is removed and now I need to know when a file is created at that "Path". As a workaround I tried to also watch the parent directory. This gives me an Access(Close(Write)) Event when a file is created. However, the path shown for this event is just the name of the watched parent directory, so I cannot map this event to the file I'm interested in.

@xanderio Ping

**Comment by xanderio** [comment]
Sorry for the late response I'm currently very busy with life stuff :(

I taken a quick look at the FreeBSD man page for kqueue. I not sure how this data is reported, we should take a look at other kqueue based file watcher implementation to figure out how to do this, it should be possible.

I currently don't have the time to do this. I'll take a look at this when thing quite down again in my life. If anyone else is willing to take a shoot at this, i'll be happy to help and review the changes.

**Comment by jmagnuson** [comment]
I was noticing this as well, and took a peek at the kqueue implementation in [fsnotify](https://github.com/fsnotify/fsnotify) (BSD-3-Clause). It looks like they have a [`fileExists`](https://github.com/fsnotify/fsnotify/blob/466b39d216616549a37ee93c7c47775f6a010790/kqueue.go#L35) map which is used to determine whether to dispatch a Create event, or not. And the resulting [logic](https://github.com/fsnotify/fsnotify/blob/466b39d216616549a37ee93c7c47775f6a010790/kqueue.go#L325) is essentially:

```
if event == Remove {
    ...
} else {
    sendFileCreatedEventIfNew(filePath, fileInfo)
}
```

so it does really look like a limitation of kqueue.

Incidentally (and a mild plug), I do [something similar](https://github.com/jmagnuson/linemux/blob/af9002f22dce68b4ab0a63bc998c5cdabce8fca6/src/events.rs#L222) in my crate `linemux` (MIT/Apache-2.0), in terms of storing non-existent files in a map when registered, and then dispatching events once created. So it's likely I'll use this logic and just key off the `Close(Write)` event that's sent to synthesize my own `Create` event. But not sure if that approach falls within the design philosophy of `notify`.

**Comment by asomers** [comment]
On FreeBSD, a newly created file should show up as an event on the parent directory with `NOTE_EXTEND`.

**Comment by jhscheer** [comment]
@asomers 
On macOS, if watching the parent directory, it's `NOTE_WRITE` for a newly created file.
However, I haven't figured out how to make use of this, because there's no file path associated with the event, so I don't know which file was added to the directory.
