### ISSUE TITLE
C interface?

### ISSUE THREAD

**Issue by SamuelMarks** [notify-rs/notify#367]
Have you considered adding a C interface, using [`cbindgen`](https://github.com/eqrion/cbindgenn) or similar?

**Comment by 0xpr03** [comment]
I don't see a reason for that, as we're basically a big c wrapper ourself. So using any of these APIs is far easier to do natively with libuv or QTs QFileSystemWatcher.

**Comment by SamuelMarks** [comment]
Thanks for the response and view

**Comment by 0xpr03** [comment]
That said: I won't stop you if you open a PR and maintain that C interface. You could also create an abstraction on top of notify to provide c wrappers.
