### ISSUE TITLE
Where is the debounce/delay?

### ISSUE THREAD

**Issue by lulujun2233** [notify-rs/notify#382]
#### System details

- OS/Platform name and version:
- Rust version (if building from source): `rustc --version`:
- Notify version (or commit hash if building from git):

- If you're coming from a project that makes use of Notify, what it is, and a link to the downstream issue if there is one:
- Filesystem type and options:
- On Linux: Kernel version:
- On Windows: version and if you're running under Windows, Cygwin (unsupported), Linux Subsystem:
- If you're running as a privileged user (root, System):
- If you're running in a container, details on the runtime and overlay:
- If you're running in a VM, details on the hypervisor:

#### What you did (as detailed as you can)

Recently, I updated my version from 5.0.0-pre.9 to 5.0.0-pre.13, I cannot find the way to delay in watcher, just like:

let inner = watcher(tx_event, Duration::from_millis(100)).expect("watcher should spawn");

#### What happened
When I create a new  file a.txt in window10, there will come two events: newfile.txt and a.txt。Without the delay setting，I will only receive the event of newfile.txt

**Comment by 0xpr03** [comment]
See #262 V5 is lacking the debouncer for now.

**Comment by lulujun2233** [comment]
I think it's a bug. Since I can only receive one event: Add newfile.txt while I need the other one: rename newfile.txt to a.txt.

**Comment by 0xpr03** [comment]
So it's not about the delay, it's about you not receiving all events ?
Because you didn't provide much info and pre-13 has no debouncer at all, the underlying immediate watcher is still the same though.

**Comment by lulujun2233** [comment]
Yes , you reminded me. I forgot to update the kind of rename. That is not the problem of debouncer. Thanks for your time and looking forward to vesion 5.0 ：）
