### ISSUE TITLE
`notify 5.0.0-pre.14` doesn't build with `kqueue 1.0.5`

### ISSUE THREAD

**Issue by lnicola** [notify-rs/notify#401]
`kqueue 1.0.5` contains a breaking change (it added some variants to a public enum), so `notify` no longer builds on some platforms when using that version. This is a `kqueue` bug, but I'm filing this here to track the problem.

Spotted in https://github.com/rust-lang/rust/pull/96476#issuecomment-1111199282=.

**Comment by 0xpr03** [comment]
Would be nice if kqueue would mark their enum non-exhaustive.

What do you intend notify to do for now ?

**Comment by lnicola** [comment]
You could pin the `kqueue` dependency, or you could just ignore the problem. I only opened this so it's known.

**Comment by 0xpr03** [comment]
Then I'll close this. Thanks for fixing it so fast.

**Comment by lnicola** [comment]
@0xpr03 might be a good idea to add a fallback arm to that match? I can't check the code, but it might not compile otherwise.

**Comment by 0xpr03** [comment]
Ah yeah, will do.

**Comment by 0xpr03** [comment]
This is actually already fixed by #399 and I missed that fact until I just looked into the main source..
