### ISSUE TITLE
Adding a watch for a large directory on a slow drive is slow.

### ISSUE THREAD

**Issue by markus-bauer** [notify-rs/notify#404]
I know the title sounds stupid, but I couldn't figure out why it should be slow, or how to make it not slow.

Here's a basic example of what I'm doing:

System:
```
ubuntu linux 22.04
rustc 1.62.0-nightly
notify verion `5.0.0-pre.15`
```
```rust
use notify::{
    poll::{PollWatcher, PollWatcherConfig},
    RecursiveMode::NonRecursive,
    Watcher,
};
use std::{path::Path, time::Duration};

fn main() {
    let path = Path::new("/path/to/dir");
    let mut watcher = PollWatcher::with_config(
        |_| {
            // nothing
        },
        PollWatcherConfig {
            poll_interval: Duration::from_millis(1000),
            compare_contents: false,
        },
    )
    .unwrap();

    watcher.watch(path, NonRecursive);
}
```
I was adding a watch for a directory with ca. 6000 images on a slow drive.
And it took more than a second just to set the watch.
Watching another directory with less files on the same drive was faster.

If I just use inotify-tools on the same dir it is immediate.

My question is:
- It looks like the time it takes to set a watch scales with the number of files in a directory (and perhaps file read speed). But why? Are the files read or stated?
- I'm realy just interested in adding a watch for a directory, not all the files inside it. Note that I'm using NonRecursive. Is that possible?

**Comment by 0xpr03** [comment]
We have to subscribe to each file individually, so it's 6000 calls and listing 6000 files.

**Comment by markus-bauer** [comment]
Thanks for the reply.

The source code explains why it's slow. I assume it's because it's calling metadata/is_dir on all files.

Is this documented? I didn't know that setting a watch needs to stat all files in that dir. That's a lot of work (or it can be in some cases).

And why do you need that?
I looked through https://www.man7.org/linux/man-pages/man7/inotify.7.html
and https://docs.rs/inotify/latest/inotify/struct.EventMask.html
but I still don't know. Superficially, It sound like watching a directory sends events for objects inside that directory.
What would happen if you didn't subscribe to subfolders like you do, and only subscribed to the main dir? What events wouldn't I get?

**Comment by 0xpr03** [comment]
> I looked through https://www.man7.org/linux/man-pages/man7/inotify.7.html

```
       Inotify monitoring of directories is not recursive: to monitor
       subdirectories under a directory, additional watches must be
       created.  This can take a significant amount time for large
       directory trees.
```

**Comment by 0xpr03** [comment]
That's essentially the problem: We have to check for subdirectories and place watches on them. This is what requires going through the whole directory.

**Comment by markus-bauer** [comment]
Yes, I obviously did read what you quoted.

It makes sense that you need to do this, if you want to watch a tree or sub-tree. But that not when watching a single directory.

But, I'm not asking you to explain inotify to me. I'm going to trust that you know more about this than me.

---

> We have to check for subdirectories and place watches on them. This is what requires going through the whole directory.

But what is the NoRecursive option for then? If I set NonRecursive I assume that you set one watch only.

From the documentation:
https://docs.rs/notify/5.0.0-pre.15/notify/enum.RecursiveMode.html#variant.NonRecursive
```
Indicates whether only the provided directory or its sub-directories as well should be watched
...
Recursive
 Watch all sub-directories as well, including directories created after installing the watch

NonRecursive
 Watch only the provided directory
```
Is there no way to subscribe to  _just_ the directory? I assumed that this is what NonRecursive means. 

But you closed this already, so that's that...

**Comment by 0xpr03** [comment]
> What is the NoRecursive option for then? If I set NonRecursive I assume that you set one watch only.

Well then yes, then it's not going through the recursive lookup. I would recommend running strace and watching how long the actual linux call takes. My guess is that the linux kernel itself has to do a lot of book keeping for this.

**Comment by markus-bauer** [comment]
Okay, I did run my example code from above with strace. I also cloned the repo and put in some print statements.

Please not again, that my example is using PollWatcher and NonRecursive.

- Running with strace shows, that there are statx calls for every file in that folder.
- It looks like the source code you linked (https://github.com/notify-rs/notify/blob/1cfcbbb6fbc39b5280d227db7289c22f12d9acf7/src/inotify.rs#L458-L465) is not actually run. The metadata calls happen here:
https://github.com/notify-rs/notify/blob/1cfcbbb6fbc39b5280d227db7289c22f12d9acf7/src/poll.rs#L313-L327
And the stat calls happen because walkdir with max_depth(1) is looping over all the files in that dir.
I don't know if that's on purpose.
- This brings up another question. Is the PollWatcher using inotify?

**Comment by 0xpr03** [comment]
So ok, sorry for missing that initially:
You're using the pollwatcher which, as described, is "Polling based Watcher implementation", so no, it just checks all files regularly.

If you want inotify, use the [INotifyWatcher](https://docs.rs/notify/5.0.0-pre.15/notify/inotify/struct.INotifyWatcher.html), or as I would recommend: The [RecommendedWatcher](https://docs.rs/notify/5.0.0-pre.15/notify/type.RecommendedWatcher.html)

**Comment by 0xpr03** [comment]
> Good that we talked about (and you linked to) inotify the whole time.

What I don't get is, why did you choose something polling based when you wanted inotify and looked up the man page ?

**Comment by 0xpr03** [comment]
Ah no worries, I just glanced over the code and assumed you're using the inotify watcher when specifically talking about inotify. The polling approach is only for 3rd party platforms or since #396 to watch syfs/procfs (listed specifically as unsupported by the manpage).

**Comment by markus-bauer** [comment]
Thanks again and I think we're done here.
