### ISSUE TITLE
Notify only catches one change.

### ISSUE THREAD

**Issue by ghost** [notify-rs/notify#428]
## System details

- OS/Platform name and version: Mac OSX 12.3.1
- Rust version (if building from source): 1.62.1:
- Notify version (or commit hash if building from git): 4.0.17

I have a project [here](https://github.com/iamtheblackunicorn/wserve). I'm trying to build a server that watches for file changes and re-serves the specified bunch of files based on changes that happen.

Now when I run `wserve -s .` in a directory. The first change is detected but not after that. What am I doing wrong?

**Comment by 0xpr03** [comment]
Closing due to original repo and poster being deleted.
