### ISSUE TITLE
Reminder: the debouncer lib.rs still has debug println

### ISSUE THREAD

**Issue by CrendKing** [notify-rs/notify#433]
https://github.com/notify-rs/notify/blob/94f1680713036cd4744df4543f660a44a435be85/notify-debouncer-mini/src/lib.rs#L177
https://github.com/notify-rs/notify/blob/94f1680713036cd4744df4543f660a44a435be85/notify-debouncer-mini/src/lib.rs#L180
https://github.com/notify-rs/notify/blob/94f1680713036cd4744df4543f660a44a435be85/notify-debouncer-mini/src/lib.rs#L208

**Comment by 0xpr03** [comment]
Good catch !

**Comment by 0xpr03** [comment]
Fixed in 0.1.2
