### ISSUE TITLE
Ignored config

### ISSUE THREAD

**Issue by road2react** [notify-rs/notify#444]
After a recent v5 pre-release, `RecommendedWatcher::new` requires a config parameter. However, right now it's being ignored:

```rs
fn new<F: EventHandler>(event_handler: F, _config: Config) -> Result<Self> {
```

Is this intentional?

**Comment by 0xpr03** [comment]
Depends on the watcher. PollWatcher is currently the only for which the config holds relevant values, and it can also be the recommended one, depending on your system.
