### ISSUE TITLE
Event handler callback called twice?

### ISSUE THREAD

**Issue by m1212e** [notify-rs/notify#446]
Win 11
Rust 1.63
notify 5.0

When using the async callback like this:
```
    let (sender, mut reciever) = mpsc::channel(1);

    let handle = Handle::current();
    let mut watcher = RecommendedWatcher::new(
        move |res| {
            let sender = sender.clone();
            handle.spawn(async move {
                sender.send(res).await.unwrap();
            });
        },
        notify::Config::default(),
    )?;
```

The callback function is called twice. The watcher is started once like this:
`watcher.watch(&path, RecursiveMode::Recursive).unwrap();`

Why does this happen? Did I miss something?

**Comment by 0xpr03** [comment]
? it's called for each event

**Comment by m1212e** [comment]
Yes but only one file gets modified. The event issued is exactly the same. Should have included that in my post, sry.

**Comment by 0xpr03** [comment]
Then you probably want the debouncer-mini crate and not raw events. See also the known-issues section about editors.

**Comment by m1212e** [comment]
Ahh I see. Thanks a lot!
