### ISSUE TITLE
Compilation fails on GH Actions on MacOS when using fsevents

### ISSUE THREAD

**Issue by jquesada2016** [notify-rs/notify#447]
I know this is something that should be working, but don't really know what's causing it, per say. I am trying to build on MacOS latest on GitHub actions. The crate is declared as follows:

```toml
notify = { version = "5.0", default-features = false, feature= ["macos_fsevent"] }
```

The compilation error I get is:

```
Compiling notify v5.0.0
error[E0432]: unresolved import `fsevent_sys`
  --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0/src/fsevent.rs:19:5
   |
19 | use fsevent_sys as fs;
   |     ^^^^^^^^^^^^^^^^^ no external crate `fsevent_sys`

error[E0432]: unresolved import `fsevent_sys`
  --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0/src/fsevent.rs:20:5
   |
20 | use fsevent_sys::core_foundation as cf;
   |     ^^^^^^^^^^^ use of undeclared crate or module `fsevent_sys`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `notify` due to 2 previous errors
```

Am I doing something obviously wrong?

For additional context, I'm running on latest nightly.

**Comment by jquesada2016** [comment]
switching feature to use `macos_kqueue` results in the same error of `fsevent_sys` not being resolved.

**Comment by jquesada2016** [comment]
Lol, it was the dumbest mistake. I mispelled |features|.

**Comment by garypen** [comment]
Not that dumb: The documentation (which I guess you copied, like I did) has:
```
notify = { version = "5.0.0", default-features = false, feature=["macos_kqueue"] }
```
Note: typo `feature=` should be `features=`
