### ISSUE TITLE
Help with migrating from v4

### ISSUE THREAD

**Issue by dre-bk201** [notify-rs/notify#450]
```rust
/// notify = "4.0.17"
fn main() {

    let (tx, rx) = std::sync::mpsc::channel();
    let mut watcher: notify::RecommendedWatcher =
        notify::Watcher::new(tx, Duration::from_secs(3)).unwrap();

    watcher.watch("C:/Users/Username/Desktop/testing", RecursiveMode::Recursive);

    for e in rx {
        match e {
            DebouncedEvent::Rename(from, to) => {
                println!("Renaming {from:?} {to:?}");
            }
             _ => ()
        }
    }
}
```
In said version of this crate I am able to match against `DebouncedEvent` for example `DebouncedEvent::Rename`and get `from` and `to`, I have not been able to reproduce this behavior in v5, the closest I've came is using v5 `notify::event::Event` `paths` field but it doesn't work the same. I have read the reason for this [upgrading from v4 to v5](https://github.com/notify-rs/notify/blob/main/UPGRADING_V4_TO_V5.md) but still is there anything that I'm overlooking?

**Comment by 0xpr03** [comment]
You can find "from" and "to" [here](https://docs.rs/notify/latest/notify/event/enum.RenameMode.html#variant.Both), they're provided in that order inside the paths, as stated in the docs.

**Comment by 0xpr03** [comment]
```rust
match e.kind {
    EventKind::Modify(ModifyKind::RenameMode(RenameMode::Both)) => {
        println!("Renaming from {} to {}",e.paths[0].display(),e.paths[1].display());
    }
    _ => ()
}
```

**Comment by dre-bk201** [comment]
Ok I get it now, thank you for the clarification.
