### ISSUE TITLE
V5 migration

### ISSUE THREAD

**Issue by longfellowone** [notify-rs/notify#451]
Hi,

Read the "Upgrading to V4" guide, and I am not sure I understand why we can't have precise events with the debouncer. But when using the non-debounced version we can?

What I am trying to do is run a function when the file is modified. I would use the non-debounced version, but for whatever reason, every time I save the file, the application rapidly saves the file 3 times, putting out 3 modify events. I only need 1 of these to trigger the function, as I don't want to needlessly run it the function 3 times? with v4 I was using the debouncer with a 10ms delay to get around this issue.

Thanks

**Comment by 0xpr03** [comment]
The problem are the ton of corner cases that surround "debouncing". Your write event could also be a truncate + write, delete + create or rename event - depending on the editor and the OS.

**Comment by 0xpr03** [comment]
That said: I'm not opposed to re-introducing a "debouncer-full" which emulates what v4 did, hopefully also fixing the issues v4 couldn't handle.

**Comment by longfellowone** [comment]
Would an alternative be to just provide the most recent event anyway, and the user decides whether to trust/take action?

I can see how checking if a file exists for the modify event might work, but how would I differentiate between and modify and a create?

**Comment by 0xpr03** [comment]
> differentiate between and modify and a create

If you mean knowing whether the file was created newly or was modified: You can't if you want to be technically correct (see above answer for editors and their behaviour).

From what I understand you just want to run the function if your file was modified with 10ms latency (quite low in my opinion). And maybe I'm missing the full picture, but I can't see why simply using the normal debounce event isn't enough for that. All you need to know is that something happened with the file. If it was created you probably also want to run the function, and if it was deleted, you'll "find out" pretty easily. I don't see the harm in running said functionality for more than "modified". You can still check the creation/change date.

**Comment by 0xpr03** [comment]
@longfellowone which solution worked for you ?
