### ISSUE TITLE
Watching a file regardless of file presence

### ISSUE THREAD

**Issue by harrisonmg** [notify-rs/notify#459]
Hello

I'm curious if anyone has an idea for watching a file that hasn't yet been created. My general goal is to have zero lapse between my program creating a file and my watcher reporting changes to that file (primarily renames and moves by other programs).

I'm sure I could watch the file directory, but my current use case has relatively strict performance requirements, and I have a feeling that watching a potentially large directory could be intensive.

My environment is Linux; I imagine notify might latch onto a file's inode, so perhaps my question has no answer. Apologies as I am not too familiar with the inner workings of notify.

Thanks!

**Comment by 0xpr03** [comment]
> I imagine notify might latch onto a file's inode

Correct, we have a file handle. You can also set the tick rate for the poll-watcher backend really low. But that sounds in general like you're trying to do something for which the whole watch-api in linux wasn't ever intended. (Which kinda of hinted by the fact that each and every file you can get a notification for is counted towards the max file watch limit.)
