### ISSUE TITLE
Compiling on Linux fails with "no `FsEventWatcher` in the root"

### ISSUE THREAD

**Issue by hb0nes** [notify-rs/notify#462]
#### System details

- OS/Platform name and version: Linux Debian Bullseye
- Rust version (if building from source): `rustc --version`: rustc 1.68.0-nightly (ee0412d1e 2023-01-07)
- Notify version (or commit hash if building from git): notify = "5.0.0"

- If you're coming from a project that makes use of Notify, what it is, and a link to the downstream issue if there is one: https://github.com/hb0nes/linux_mail_db
- Filesystem type and options: ext4
- On Linux: Kernel version: Linux ld4-sys-01 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
- If you're running as a privileged user (root, System): root

#### What you did (as detailed as you can)
Tried to compile on Linux.
I developed on an Mac M1 without issues.

#### What you expected
FsEventWatcher to be available and the compilation to succeed.

#### What happened
```
   Compiling mail-checker v0.1.0 (/home/shared/hbonnes/code/linux_mail_db)
error[E0432]: unresolved import `notify::FsEventWatcher`
 --> src/tail.rs:7:40
  |
7 | use notify::{Config, Event, EventKind, FsEventWatcher, RecommendedWatcher, RecursiveMode, Watcher};
  |                                        ^^^^^^^^^^^^^^ no `FsEventWatcher` in the root
```

**Comment by hb0nes** [comment]
I've fixed it by replacing FsEventWatcher with RecommendedWatcher. No idea how FsEventWatcher got in there. I think my CLion inferred it somehow.

**Comment by JohnTitor** [comment]
`FsEventWatcher` is for macOS, you should use other watchers like `INotifyWatcher` on other platforms. Yes, `RecommendedWatcher` will pick up the _best_ watcher for your platform using cfgs.

**Comment by hb0nes** [comment]
Yeah, pretty sure the IDE picked up on that and decided to import that type
without me noticing. Unfortunately my knowledge is way too little to have
debugged this properly (why is this type in the root on Mac but not on
Linux..?) and I just stumbled upon the 'solution' by sheer luck while
looking at Notify examples in the repo.
