### ISSUE TITLE
`notify-debouncer-mini` always does busy waiting

### ISSUE THREAD

**Issue by kchibisov** [notify-rs/notify#466]
Previously the notify v4 were doing passive waiting with at least inotify(and it was falling back to polling each X ms), meaning that it was woken up only when something was actually changing, with notify v5 we have constant CPU draining when using the `notify-debouncer-mini`.

How could we avoid such a thing and do passive waiting instead like it was by default before? From reading the documentation it's not clear to me how to avoid that, maybe we should use the notify directly here?

**Comment by kchibisov** [comment]
The reference code we're using is here https://github.com/alacritty/alacritty/blob/master/alacritty/src/config/monitor.rs.

I'm not sure how I've missed that issue during udpate to notify v5 initially, but what we want is passive wait and wake-up on inotify/kqueue events, we're fine with spawning extra loop just for that, like we do before.

Right now the situation is that we notify-rs thread is draining around 3% of CPU on my machine.

**Comment by kchibisov** [comment]
I've investigated a bit more on my issue, and the issue I'm having is that `notify-debouncer-mini` always do busy-wait, which is not desired.

The default documentation is not really clear what is doing active polling or not, but I've figured that only `poll` will do that in notify (which is fine) and that `Config::with_poll_interval` doesn't mention that it's used **if and only if** busy polling is the only option in `RecommendedWatcher`.

I've solved my issue implementing minimal naive debouncer on top of `RecommendedWatcher`, see https://github.com/alacritty/alacritty/pull/6653.

So, given that original title doesn't reflect the issue anymore, I'll update it.

**Comment by 0xpr03** [comment]
What exactly do you use for the debounce settings ? Because that obviously affects how often this runs.

Related #442

**Comment by kchibisov** [comment]
>Is there a reason to have such a low timeout for now ? Because that would be the fastest fix.

@0xpr03 but why should I have any busy waiting in the first  place? Right now I've fixed by writing a ~12 lines debouncer(it's not optimal if you spam it, but  that is fine for) that does real non-busy polling https://github.com/alacritty/alacritty/pull/6653 without any complexity of mini deobouncer.

**Comment by 0xpr03** [comment]
Note that your code removes the 10ms timeout and replaces it with a 1s timeout. Which in itself is already the obvious fix. Your code also won't work for continuous events. All I need to do is change a file every 999ms and you'll never debounce, nor emit continuous events, just blow up the received_events vec. (I also advice against creating a Vec with capacity 0.)

**Comment by kchibisov** [comment]
>No wait, your channel will still timeout every 10ms. That's not a real passive polling, which would go to sleep until new events come in, if nothing happened and the buffer is empty.

It'll timeout **if and only if** I've got an event. But the mini debouncer **always** busy waits with an extra thread. There's no way to do what I'm doing of waiting with recv timeout. So what I have is passive polling until the event in each branch.

>Your code also won't work for continuous events. All I need to do is change a file every 999ms9ms and you'll never debounce, nor emit continuous events, just blow up the received_events vec. (I also advice against creating a Vec with capacity 0.)

Yeah, I've mentioned that, but it's easily fixable and I mentioned that we don't really care, though I might fix it as well(same logic just change the timoout on the fly).

>I also advice against creating a Vec with capacity 0.)

I create it with capacity of `8`.

**Comment by 0xpr03** [comment]
Hm ok, looking at this from my desktop you're right. This could be used, but I can't see how I can shutdown your loop cleanly if no events happen (which might be totally fine for your code).

> I create it with capacity of 8.

Yeah ok, I should probably increase my font size 🙈

**Comment by kchibisov** [comment]
>Hm ok, looking at this from my desktop you're right. This could be used, but I can't see how I can shutdown your loop cleanly if no events happen (which might be totally fine for your code).

Yeah, for custom wait what I'd need is to change the channel to do the following:

1. Abstract event handler that will have `Shutdown` and normal `Event`.
2. Your debouncer should call the `proxy.send(Event::Shutdown)` from the destructor and joining the thread. That will shutdown the inner thread and clean-up the resources.

That probably all be it. You'll have clean shutdown, no busy waiting and such.

Just as a side not, my code is irrelevant, since we don't do any clean shutdown(though, that would be nice).

**Comment by 0xpr03** [comment]
> Abstract event handler that will have Shutdown and normal Event.

You mean changing notify to send a shutdown event, so the debouncer knows when it should shutdown ?

**Comment by kchibisov** [comment]
Can't you create a custom `impl EventHandler` with the channel using the following data type for the channel?

```rust
enum DebouncerEvent {
  Event(notify::Event),
  Shutdown,
}
```

Then for the user you pass the `notify::Event`?

I can probably write-up something tomorrow and see how it goes.

**Comment by 0xpr03** [comment]
I'm currently implementing something, it's actually little harder as I'm trying to avoid using a channel internally. And the debouncer doesn't know when notify shuts down, so I'll have to do that on debouncer drop.
