### ISSUE TITLE
error[E0599]: no method named `into_i32` found for enum `timeout::Timeout` in the current scope

### ISSUE THREAD

**Issue by Miniontoby** [notify-rs/notify#469]
#### System details

- OS/Platform name and version: github runner with ubuntu-latest image
- Rust version (if building from source): latest
- Notify version (or commit hash if building from git): 4
- If you're coming from a project that makes use of Notify, what it is, and a link to the downstream issue if there is one: https://github.com/tauri-apps
- Filesystem type and options: Ubuntu
- On Linux: Kernel version: latest version?
- If you're running in a container, details on the runtime and overlay: github runner?

#### What you did (as detailed as you can)

I just let github actions build my [tauri app](https://tauri.app/) and then it gave the error that I placed in the `What happened` section. This was just during the build. P.s. This only happens at the Ubuntu OS, I was also having the same issue with my mobile build, but removed the dependency because it might not had been added (and this was together with some other errors, but that could be handled in a different issue)

#### What you expected

No errors or exceptions

#### What happened

```
error[E0599]: no method named `into_i32` found for enum `timeout::Timeout` in the current scope
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-4.5.10/src/xdg/zbus_rs.rs:72:38
   |
72 |                 notification.timeout.into_i32(),
   |                                      ^^^^^^^^ method not found in `timeout::Timeout`
   |
  ::: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-4.5.10/src/timeout.rs:3:1
   |
3  | pub enum Timeout {
   | ---------------- method `into_i32` not found for this enum

For more information about this error, try `rustc --explain E0599`.
error: could not compile `notify-rust` due to previous error
warning: build failed, waiting for other jobs to finish...
       Error failed to build app: failed to build app
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

- Miniontoby

**Comment by JohnTitor** [comment]
The error is about the `notify-rust` crate, not `notify`, you should visit https://github.com/hoodie/notify-rust instead.

**Comment by hoodie** [comment]
sorry about the naming overlap everybody :D
