### ISSUE TITLE
I use notify to watch a path which is mount by nfs，notify didn't work and no error return

### ISSUE THREAD

**Issue by co0ontty** [notify-rs/notify#475]
#### What you did (as detailed as you can)

I use notify to watch a path which is mount by nfs，notify didn't work and no error return

#### What you expected

I want recive a error when notify can't watch this path

**Comment by 0xpr03** [comment]
You need to use the [PollWatcher](https://docs.rs/notify/latest/notify/poll/struct.PollWatcher.html) for network mounts. See also [stackoverflow](https://stackoverflow.com/a/4231277/3332686).

Notify can't tell whether this will work, as the kernel just doesn't send any events for the NFS mount.

**Comment by co0ontty** [comment]
If possible, can you return an error when the nfs type appears in the directory?

**Comment by 0xpr03** [comment]
We don't know when something is NFS. As far as I know, we would have to scan your mounts and detect an NFS system, even across soft- and hard-links. That seems out of scope to me.
