### ISSUE TITLE
Multiple paths clarification 

### ISSUE THREAD

**Issue by chipsenkbeil** [notify-rs/notify#490]
I'm trying to understand when an event would have multiple paths listed.

For non-rename events, I'm assuming multiple paths can be bundled by the underlying watcher such as two different paths being modified.

For rename, is it exactly two paths if we know the before and after? For rename from and to events, are they always a single path? Or could they still have multiple?

What does it mean if rename has three or more paths? How do we derive meaning from the order in that situation?

I'm leveraging notify today and wanted to send individual updates over a channel for each path, but I also need to distinguish old paths in rename events (I'm assuming).

**Comment by 0xpr03** [comment]
There shouldn't be a case where you have more than one path for a rename. At least from what I know.
The event type does allow for this, but that's just part of making it generic over the event kind.

(Based on my experience I wouldn't wonder if someday some OS does emit 3 or more paths for a rename..)

**Comment by chipsenkbeil** [comment]
Okay, great. Thanks for the clarity!
