### ISSUE TITLE
Debouncers don't implement Debug

### ISSUE THREAD

**Issue by awused** [notify-rs/notify#509]
Thanks for maintaining this.

It's a minor thing but right now it's annoying to use the debouncers (either of them) as a drop-in replacements for watchers since they don't implement Debug.

**Comment by 0xpr03** [comment]
You mean adding Debug to the Debouncer, so you can print it like the Backends (like PollWatcher)?


Do you need any meaningful data from that debug print ?

**Comment by awused** [comment]
It's not really about printing anything useful - and it shouldn't it's about not getting in the way of existing derive(Debug) implementations.

I can have this struct in my program:
```rust
#[derive(Debug)]
struct MyStructWithWatcher {
    map_of_something: HashMap<String, usize>,
    // Whatever other other program state is relevant

    watcher: RecommendedWatcher
}
```

But this similar struct will fail to compile.
```rust
#[derive(Debug)]
struct MyStructWithDebouncer {
    map_of_something: HashMap<String, usize>,
    // Whatever other other program state is relevant

    watcher: Debouncer<RecommendedWatcher>
}
```

If MyStruct is some existing struct where I wanted to replace a Watcher with a Debouncer I now need to work around this !Debug field with some kind of newtype wrapper or write my own debug implementation. In general all types in public APIs should derive Debug if only so they don't get in the way, there's also official rust api guidelines on this, though I don't know how many projects really bother to follow them all. https://github.com/rust-lang/api-guidelines/blob/master/src/debuggability.md

**Comment by 0xpr03** [comment]
I see, makes sense.
