### ISSUE TITLE
Potential Double Free Issue

### ISSUE THREAD

**Issue by kuzeyardabulut** [notify-rs/notify#516]
Hi,
I found a memory-safety/soundness issue in this crate while scanning Rust code for potential vulnerabilities. This PR contains a fix for the issue.

# Issue Description
https://github.com/notify-rs/notify/blob/5f40b83c04b04893a42f91b55e4ceeef3777d47c/notify/src/windows.rs#L281-L310

If a panic!() occurs between the `Box::new()` function and `std::mem::forget`, a double free vulnerability emerges.

# Fix
In Rust, `std::mem::forget` does not actually free the memory, instead it simply allows the memory to leak. This can lead to double free when the data object goes out of scope and its destructor is called automatically. The modification here uses `std::mem::ManuallyDrop` to wrap data. This ensures that data will not be automatically dropped when it goes out of scope, thus avoiding a double free scenario. With `ManuallyDrop`, we explicitly state that the data variable should not be dropped, thus avoiding any potential double free issues.

**Comment by 0xpr03** [comment]
Hi, thanks for reporting.
Adding `ManuallyDrop` doesn't seem to be wrong. However I can't find any way this could panic - at least not in a way that it creates a problem. The only thing that could panic is `ReadDirectoryChangesW` itself, which would mean the C-API of windows is panicking, as it's a [direct wrapper](https://docs.rs/windows-sys/0.48.0/windows_sys/Win32/Storage/FileSystem/fn.ReadDirectoryChangesW.html#).

**Comment by kuzeyardabulut** [comment]
Thanks for your answer. For now, there is no possible panic!() here, but it may be important to fix this error for the progress of the project.

I will create a PR. Please let me know if there is any mistake.
