### ISSUE TITLE
notify crate not actually including license text

### ISSUE THREAD

**Issue by erickt** [notify-rs/notify#526]
In https://github.com/notify-rs/notify/issues/514, I requested that the license text be included in the crate. This was supposed to be fixed in https://github.com/notify-rs/notify/pull/464, but it appears that the text hasn't actually gotten into the crate. This can be easiest to see on docs.rs:

* [LICENSE](https://docs.rs/crate/notify/latest/source/LICENSE)
* [LICENSE.ARTISTIC](https://docs.rs/crate/notify/latest/source/LICENSE.ARTISTIC)

Are the releases being cut from a windows machine? If that's the case, I'm guessing these files are symlinks on unix, but maybe windows isn't interpreting them as symlinks, and is just including their contents?

**Comment by 0xpr03** [comment]
> Are the releases being cut from a windows machine

Yep, that's the issue. But it shouldn't be the case anymore since #520 with the upcoming release.

**Comment by 0xpr03** [comment]
[Fixed](https://docs.rs/crate/notify/latest/source/LICENSE-CC0) by #520
