### ISSUE TITLE
Filtering out `log` logs

### ISSUE THREAD

**Issue by szattila98** [notify-rs/notify#539]
Hello, I would like to use this crate in my application in an async manner inside `tokio::spawn`. I got it working fine but my problem is that every time a file event happens. It seems logs get published by the `log` crate. I use the `tracing` crate in my application and these logs do not conform to the rules it sets. At first I thought that the logs are in a different span and that is why they are unruly but I made them use the current span and still they come. Can you give me some pointers how to filter out the logs emitted by notify? I could not find a way online, as it is kinda hard to google, given the `log` crate name :D

**Comment by szattila98** [comment]
Well as always I immediately find a solution after posting an issue, but not before searching for hours :D 
I turned off the `tracing-log` feature on `tracing-appender` and it turned off all crate emitted logs. I am still curious if there are better options to tune the logs emitted to my liking.

**Comment by 0xpr03** [comment]
You set the global log to something like warn and then set your crate log higher.

[Example](https://github.com/0xpr03/nitter-status/blob/6201f6dd4460a16e0ab3b8c463d88b73a46c46c1/src/main.rs#L37-L49) from my code. Sets the global logger to warn, and then lowers it for specific crates.

Or you set the global one low (trace) and some specific ones high (warn) for this crate - but that usually doesn't work out, as pulling in axum/tokio will already get you a ton of those different crates.
