### ISSUE TITLE
My program stops getting events after some time

### ISSUE THREAD

**Issue by ShayBox** [notify-rs/notify#545]
I use `notify-rs` in my `VRC-LOG` project [here](https://github.com/ShayBox/VRC-LOG/blob/master/src/main.rs#L18) and [here](https://github.com/ShayBox/VRC-LOG/blob/master/src/lib.rs#L17)

I'm on `Windows 11 23H2` using the latest version of `notify-rs` and my program stops getting events after about 10–30 minutes, do you know what might be causing this? This has been a problem since the start of my project, it's not new.

I tried adding prints to the callbacks, but they just stopped getting events altogether.

EDIT: Though I ignore send errors now, I previously unwrapped and never found an exception.

**Comment by 0xpr03** [comment]
Looks like a duplicate of #482. You have to keep the watcher, dropping it like [here](https://github.com/ShayBox/VRC-LOG/blob/cc12a83583901e2423b25131c466dc23a18aede7/src/lib.rs#L39) stops the event loop.

**Comment by ShayBox** [comment]
Ah, that makes sense... I discovered the same thing about the channels, but didn't occur to me the watcher is the same. 🤦 Thank you

**Comment by ShayBox** [comment]
Maybe an opt-out info/debug message on drop would be useful, I've run into this issue multiple times using this library and never realize it.
