### ISSUE TITLE
Prepare notify 7.0 release

### ISSUE THREAD

**Issue by dfaust** [notify-rs/notify#560]
The change of the event serialization (#558) requires a release of a new major version.
Are there other breaking changes that we should make before rolling a new release?

My suggestion:
- Remove `crossbeam-channel` from the default features

**Comment by 0xpr03** [comment]
#525  possibly

**Comment by 0xpr03** [comment]
Also +1 for removing crossbeam channel.
It's a safe bet that it will be part of the std anyway.

**Comment by kaimast** [comment]
It would be great if you could update to mio 1.0 for the next release.

**Comment by dfaust** [comment]
@0xpr03, @JohnTitor 
I would like to merge #630 and then release a new version. Maybe an RC first.
Also, I was thinking about yanking notify-debouncer-full 0.3.0 and 0.3.1 because of the panic found in #636.
Any objections?

**Comment by 0xpr03** [comment]
Sounds good to me.
