### ISSUE TITLE
Zbus / Nix Dependency Issue

### ISSUE THREAD

**Issue by nadenf** [notify-rs/notify#562]
So there is an odd situation where Zbus has a dependency on Nix but didn't correctly specify it whereas some other library did which has now removed it. 

Which in turn is causing Notify (latest version 4) to not compile on Ubuntu Linux with the following error:
```
error[E0432]: unresolved import `nix::unistd::Uid`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.14.1/src/address.rs:9:5
   |
   | use nix::unistd::Uid;
   |     ^^^^^^^^^^^^^^^^ no `Uid` in `unistd`
   |
note: found an item that was configured out
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.26.4/src/unistd.rs:73:12
   |
   | pub struct Uid(uid_t);
   |            ^^^
   = note: the item is gated behind the `user` feature
```

There is a PR [here](https://github.com/dbus2/zbus/pull/568) which fixes it but you may want to temporarily fix this. 

Reddit [thread](https://www.reddit.com/r/learnrust/comments/1ais66w/cannot_get_slint_template_to_compile/) which is discussing this issue as it affects other libraries as well.

**Comment by 0xpr03** [comment]
Does that even affect notify? It sounds more like users of zbus have to upgrade such that relevant feature is selected. https://github.com/dbus2/zbus/pull/568
