### ISSUE TITLE
Full CPU core usage with the Inotify backend

### ISSUE THREAD

**Issue by tareksander** [notify-rs/notify#566]
#### System details

- OS/Platform name and version: Debian 12
- Rust version (if building from source): `rustc --version`: 1.76.0
- Notify version (or commit hash if building from git): 6.1.1

- Filesystem type and options: ext4 (rw, relatime)
- On Linux: Kernel version: 6.1.0

#### What you did (as detailed as you can)

Watch a directory (".") with ~5 files and no folders recursively, with the default watcher (it selected inotify).

#### What you expected

Since inotify waits for events, the thread should block when nothing is happening.

#### What happened

I get a full core CPU of usage, even with no events.

**Comment by 0xpr03** [comment]
This sadly has no code or any information what your event prints looks like.
