### ISSUE TITLE
Relax windows-rs version requirement

### ISSUE THREAD

**Issue by simonask** [notify-rs/notify#574]
`notify` currently asks for `windows 0.48.0`, which prevents Cargo from using newer version of the crate.

The only reason to stay on `windows 0.48.0` is that it's the last version to support Rust 1.48, but `notify` uses `edition = "2021"`, which was first supported i Rust 1.56.

Many crates in the ecosystem depend on the `windows` crate, and it adds quite a bit to compile times. This is a problem because multiple versions of the crate end up getting compiled. In my case, I currently have 4 versions (!!) of `windows` in my build, and `notify` is by far the oldest.

Relaxing the requirement to just `0.48` (without the patch version) should allow Cargo to select newer versions of the crate.

**Comment by waywardmonkeys** [comment]
@simonask Changing from `0.48.0` to `0.48` won't help here. The newer version being used is `0.52` and that won't get used automatically due to how versions under `1.0` are handled by cargo.

There are already a couple of PRs that update this to 0.52, so hopefully they'll land and we'll get a v7.

**Comment by simonask** [comment]
Ah, I see, that's unfortunate. I'm closing this issue now, since windows-rs seems unlikely to reach 1.0 anytime soon. Feel free to reopen if you want to keep this around. :-)
