### ISSUE TITLE
I have to specify all possible event kinds in match statement, instead of using any.

### ISSUE THREAD

**Issue by saverioscagnoli** [notify-rs/notify#588]
#### System details

- OS/Platform name and version: Fedora Linux 40, Hyprland
- Rust version (if building from source): `rustc --version`: rustc 1.77.2 (25ef9e3d8 2024-04-09)
- Notify version (or commit hash if building from git): 6.1.1

- Filesystem type and options: btrfs
- Kernel version: 6.8.7-300.fc40.x86_64 
- If you're running as a privileged user (root, System): No

#### What you did (as detailed as you can)

I am using Tauri to make a file explorer, and I am using notify to watch for changes in the workspace directory. So, if it is modified externally, the changes still appear.

I am watching a directory, let's say ~/Downloads, with this logic:
```rs
pub fn watch(path: impl AsRef<Path>, event_emitter: EventEmitter) {
  let (tx, rx) = std::sync::mpsc::channel();

  let mut watcher = RecommendedWatcher::new(tx, Config::default()).unwrap();

  watcher.watch(path.as_ref(), RecursiveMode::NonRecursive).unwrap();

  for res in rx {
    match res {
      Ok(event) => {
        println!("changed: {:?}", event);
        match event.kind {
          | EventKind::Create(CreateKind::Any)
          | EventKind::Remove(RemoveKind::Any)
          | EventKind::Modify(ModifyKind::Any) => {
            if let Some(path) = event.paths.first() {
              let dir = path.parent();
              println!("watch dfddfdevent: {:?}", event.kind);
              event_emitter.emit(Event::WatchDir, dir);
            }
          }
          _ => {
            println!("unhandled :(");
            return;
          }
        }
      }
      Err(e) => println!("watch error: {:?}", e),
    }
  }
}
```
But when I create a file/folder or try to delete a file in the path specified, it prints "unhandled :("

instead I have to modify the match statement like this:

```rs
        match event.kind {
          | EventKind::Create(CreateKind::Folder)
          | EventKind::Create(CreateKind::File)
          | EventKind::Create(CreateKind::Other)
          | EventKind::Remove(RemoveKind::File)
         // Continue for each kind...
        => {}
```

With this, it works and correctly triggers the event I want.
Is this a bug? I am using notify incorrectly?
Sorry if it is a stupid question I am new to rust and trying to understand how it works.

**Comment by 0xpr03** [comment]
As documented Any is another option, if the source can't be determined. Rust enums can't be two things at the same time - which would be necessary to allow matching over `CreateKind::Folder` or `CreateKind::Folder`.

My recommendation is to use one of the [two debouncer crates](https://crates.io/search?q=notify-debouncer). This is perfect for wanting "any" and not having to solve the hard problem of debouncing, handling renames and doing that cross OS.

**Comment by saverioscagnoli** [comment]
> As documented Any is another option - excluded from the ones listed, if the event source can't be determined. Rust enums can't be two things at the same time - which would be necessary to allow matching over `CreateKind::Folder` or `CreateKind::Folder` to get Folder events.
> 
> My recommendation is to use one of the [two debouncer crates](https://crates.io/search?q=notify-debouncer) instead of directly working with notify. This is perfect for wanting "any" and not having to solve the hard problems of debouncing, handling renames and doing that cross OS. You probably want debouncer-full.

I see, thank you very much!
