### ISSUE TITLE
Q. How to ignore tracking some folders/files inside tracked folder?

### ISSUE THREAD

**Issue by Ashu999** [notify-rs/notify#598]
example:
```bash
TrackedFolder
      .Folder1
      Folder2
      File1.ext
      File2.ext
```
Let's say I have watcher enabled on `TrackedFolder`. I want to exclude `.Folder1` from getting tracked. How to achieve it?

**Comment by bicarlsen** [comment]
From my delve into the crate, this isn't currently possible. It is left to the client application to filter based on the `Event`'s paths.

(e.g. [code ref](https://github.com/notify-rs/notify/blob/ade84e838bc03d9191145933cbba14e01014beac/notify/src/inotify.rs#L400))

**Comment by 0xpr03** [comment]
There is no filtering in notify right now. I recommend making this a MR against debouncer-mini and -full.
Having an ignore on the level of notify will be hard.
