### ISSUE TITLE
Windows sends Create<Any> but MacOS and Linux send Create<File>

### ISSUE THREAD

**Issue by yatesco** [notify-rs/notify#633]
Hi,

I'm not sure if this is a bug or not, but I can reproduce this very easily (in fact, I can't prevent this happening!). When I run the following code and then delete and create a file in the `idx_dir`:
```rust
fn do_it(idx_dir: &PathBuf) {
    let (tx, mut rx) = unbounded_channel();
    let mut watcher = RecommendedWatcher::new(
        move |res| {
            tx.send(res).expect("TODO");
        },
        Config::default(),
    )
    .unwrap();

    // TODO - unwrap()
    watcher.watch(&idx_dir, RecursiveMode::Recursive).unwrap();

    while let Some(res) = rx.recv().await {
        println!("IN LOOP received: {:?}", &res);
    }
}
```

On MacOS and Linux I see:

```log
IN LOOP received: Ok(Event { kind: Remove(File), paths: ["/Users/coliny/Dev/com.qfi.health/pj-health-fs/fs/event-log-cache/meta/latest/366"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
IN LOOP received: Ok(Event { kind: Create(File), paths: ["/Users/coliny/Dev/com.qfi.health/pj-health-fs/fs/event-log-cache/meta/latest/367"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
```

but on Windows I see:

```log
IN LOOP received: Ok(Event { kind: Remove(Any), paths: ["c:/pj-health-fs/fs\\event-log-cache\\meta\\latest\\301708"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
IN LOOP received: Ok(Event { kind: Create(Any), paths: ["c:/pj-health-fs/fs\\event-log-cache\\meta\\latest\\301709"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None })
```

Note the `Kind` variant in MacOS and Linux is `Kind::File`, which is helpful, but on Windows *only* `Kind::Any` variants appear (i.e., the `Kind::File` variant never arrives).

To be explicit - all examples are run on "simple" filesystems (i.e. no sym/hard links/SMB shares/nested mount points etc.).

Is this surprising/a bug, or is this just the "fun of working with Windows"? :-)

Thanks!

**Comment by dfaust** [comment]
> Is this surprising/a bug, or is this just the "fun of working with Windows"? :-)

This is to be expected. The FS notification systems vary wildly between platforms.

Best practice is to rely on as little information from the FS events as possible. Or in other words, always handle the `Any` events.
