### ISSUE TITLE
instant crate is unmaintained

### ISSUE THREAD

**Issue by jplatte** [notify-rs/notify#651]
The [instant](https://crates.io/crates/instant) crate is unmaintained. I would send a PR to replace it with `web_time` as suggested in `instant`s readme, but it seems like `notify-types` (which currently uses `instant`) is at v1.0.0, so maybe you don't want to change public dependencies at this point?

**Comment by dfaust** [comment]
Hey @jplatte, thanks for the offer. I was a bit late to answer and now there's already a PR: https://github.com/notify-rs/notify/pull/652
